### PR TITLE
[components]: Search functionality feature on website

### PR DESCRIPTION
**Pull request by khalilcodes**
## Search component
Tasks from #34 
***

This PR adds a doc search feature to the website.

### Tasks
- [x] Create search component and add to navbar
- [x] Add styles for search modal
- [x] Algolia package as specified in docs - https://docsearch.algolia.com/docs/DocSearch-v3 

### Notes
Required to add algolia configs as env variables: 
- API key, 
- App ID, 
- Index name

### Screenshots

Screen Shot 2022-08-03 at 8 29 38 PM

Screen Shot 2022-08-03 at 8 29 51 PM

### CODE REVIEW

**Review by rufuspollock — CHANGES_REQUESTED** [review]
Looks fine to me - one thing missing are some short docs ...

**Comment by rufuspollock** [comment]
@khalilcodes this now has conflicts so i can't merge.

**Comment by khalilcodes** [comment]
Yes will merge along with added docs.

**Comment by khalilcodes** [comment]
The build seems to be failing here for some reason (suspecting package-lock after merge). Here's some more info on why the build can fail - https://nextjs.org/docs/messages/failed-loading-swc 

I will close this and create a new branch with PR.

**Pull request closed without merging**
