### PR TITLE
[Fix]: Responsive styles

### PR DESCRIPTION
**Pull request by khalilcodes**
## Fix navbar, footer and button / form styles

This PR adds responsive layout styles for navbar (with search component in mobile menu), footer and the signup button in docs.

### Tasks
- [x] fix navbar layout on mobile
  - [x] add the search component in nav menu
- [x] fix footer layout overflow on mobile
- [x] fix button style which was large on mobile
- [x] update tailwind package to support new feature eg. `<div className="[&>*]:bg-white" />`

### Screenshots
- Navbar (mobile)
Screen Shot 2022-08-30 at 10 49 25 PM

Screen Shot 2022-09-01 at 11 28 45 AM

- Navbar (tablet)
Screen Shot 2022-08-30 at 10 50 28 PM

- Footer (mobile)
Screen Shot 2022-08-30 at 10 53 07 PM

- Button (in docs)
Screen Shot 2022-08-30 at 10 57 42 PM

### CODE REVIEW

**Review by olayway — CHANGES_REQUESTED** [review]
Thank you @khalilcodes for taking care of this.
There are two things I've noticed:
1. There is a point at wich navbar content still wraps:
image
2. I'd move the search input to the top of the sidebar, above the navlinks

**Comment by khalilcodes** [comment]
@olayway changes have been updated

**Comment by khalilcodes** [comment]
@olayway changes have been updated

**Review by olayway — APPROVED** [review]
Looks good, thank you!

**Pull request merged**
