### PR TITLE
Enable changesets in flowershow

### LINKED ISSUE #16: Use changesets
Set up https://github.com/changesets/changesets for this repo and briefly document it into the developer workflow

Good recent setup instructions https://dnlytras.com/blog/using-changesets/

## Acceptance

* [ ] We are using changesets to track changes e.g. one changeset example
* [ ] Automating doing releases and pushing to npm via github actions (?)
  * [ ] register @flowershow org on npm
  * [ ] github action
* [ ] short docs on our use of changests in developer docs e.g. https://flowershow.app/docs/developers

## Tasks

* [x] Quick research on how to do this
* [x] Recommend whether to proceed (e.g. are benefits worth the costs)
* [ ] Next steps ...
* [ ] ...

### PR DESCRIPTION
**Pull request by abhishekgahlot**
Fixes #16 

## Usage

`npm run changeset`

## Release
`npm run release`

### CODE REVIEW

**Comment by rufuspollock** [comment]
@abhishekgahlot for now can you fix the conflicts and we'll merge this and add the documentation later ...

**Comment by abhishekgahlot** [comment]
@rufuspollock resolved all the conflicts and is ready to be reviewed.

**Comment by rufuspollock** [comment]
@abhishekgahlot this has conflicts again - i think this and eslint branch are in conflict. Can you resolve the conflicts?

**Comment by abhishekgahlot** [comment]
@rufuspollock i have resolved conflicts and updated the change.

**Pull request merged**
