### PR TITLE
[feat]: Link previews on hover

### PR DESCRIPTION
**Pull request by khalilcodes**
### Summary
Tasks from #36 

This PR will add tooltip previews to internal links (ie. other pages of the site) with an option to disable them in config.

### Changes

* Create a tooltip component
* Add tooltip styles
* Add a property called `linkPreviews` in `config/siteConfig.js`
* Add packages - `@floating-ui/react`, `framer-motion`, `marked`

### CODE REVIEW

**Comment by olayway** [comment]
@khalilcodes it seems you have added some new dependencies by running `npm install` in `packages/template` folder instead of running `pnpm add <pkg> -F @flowershow/template` in the root of the workspace. That's why all the tests are failing with the following error:

image

**Comment by khalilcodes** [comment]
@olayway oh right 😅  will update now

**Comment by olayway** [comment]
@khalilcodes can you fix it, please? 🙏

**Comment by khalilcodes** [comment]
@olayway can you check e2e failing ?

**Comment by olayway** [comment]
@khalilcodes 
image

**Comment by rufuspollock** [comment]
Will close this and resubmit a version once monorepo is done.

**Pull request closed without merging**
