### PR TITLE
Add eslint and prettier

### PR DESCRIPTION
**Pull request by abhishekgahlot**
Following standard lint file and using prettierrc for formatting.

### CODE REVIEW

**Comment by rufuspollock** [comment]
@abhishekgahlot before getting a review i think you need the build not to fail ...

**Comment by abhishekgahlot** [comment]
@rufuspollock Yes, i am adding an option that doesn't run `linter` on build. Currently build is running linter when its called.

**Comment by rufuspollock** [comment]
@abhishekgahlot looks good. could you briefly add docs to e.g. `/docs/developer` of how this should be used.

Also do we want some kind of github actions like this as per e.g. https://playbook.datopian.com/style-guide/javascript/linting/#github-actions

**Review by rufuspollock — COMMENTED** [review]
@abhishekgahlot looks good. could you briefly add docs to e.g. /docs/developer of how this should be used.

Also do we want some kind of github actions like this as per e.g. [playbook.datopian.com/style-guide/javascript/linting/#github-actions](https://playbook.datopian.com/style-guide/javascript/linting/#github-actions)

**Comment by rufuspollock** [comment]
@abhishekgahlot is this now good to review for merging?

**Comment by abhishekgahlot** [comment]
@rufuspollock its good to go for review.

**Review by rufuspollock — APPROVED** [review]

**Pull request merged**
