### PR TITLE
Sitemap generation and documentation

### LINKED ISSUE #355: Sitemap generation
When building my site I want to generate a sitemap so that search engines pick up on all my site pages

## Acceptance

- [ ] Sitemap is generated with all pages
- [ ] Should not list "private" pages or similar

## Tasks

- [ ] Brainstorm an implementation
  - [ ] What is a sitemap
  - [ ] Look at how pliny does this - https://github.com/timlrx/pliny (note a bug https://github.com/timlrx/pliny/pull/83)
  - [ ] What nextjs libraries / approaches for this

## Notes

Approach analysis:

* nextjs docs has an implementation of adding a sitemap to pages `pages/sitemap.xml.js` which has a generate function. This uses `getServerSideProps` but I thiink this can test it out with `getStaticProps` too.
  * https://nextjs.org/learn/seo/crawling-and-indexing/xml-sitemaps
* pliny's approach is running a post build script that generates a sitemap in `/public` similar to how we have for search.json
  * also uses a globby package
  * vercel has a repo with similar implementation - https://github.com/vercel/next.js/tree/canary/examples/with-sitemap
* next-sitemap - https://github.com/iamvishnusankar/next-sitemap
  * config file in template - `next-sitemap.config.js`
  * add post build script in `package.json` - `"postbuild": "next-sitemap"`

### PR DESCRIPTION
**Pull request by khalilcodes**
Closes #355 

### Summary

This PR adds support for auto generating sitemaps in public folder if the `authorUrl` property is set in `config.mjs`

### Changes
* Config file extension changed to `config.mjs` in `template` and `template-e2e`
* Flowershow CLI updated to replace/create `config.mjs`
* Add sitemap generation script
  * generates sitemap only if `authorUrl` present in config
* Update search script
  * generates `search.json` only if using local search provider ie. kbar
* Add dev dependencies - `globby`, `prettier`, `esbuild-register`
* Add documentation @ [docs/sitemap](https://deploy-preview-454--spectacular-dragon-c1015c.netlify.app/docs/sitemap)

Todo: publish cli

### CODE REVIEW

**Comment by khalilcodes** [comment]
@olayway please review esp cli change for config. I have also added renaming `config.js` to `config.mjs` if exists.

**Review by olayway — APPROVED** [review]
LGTM :) Just some minor suggestions to the docs page.

And also, do you know why the tests are failing?

**Comment by khalilcodes** [comment]
@olayway 
> And also, do you know why the tests are failing?

I changed the config extension to `.mjs` in the tests folder too.

**Comment by khalilcodes** [comment]
@olayway please add me as collaborator for flowershow cli

**Comment by olayway** [comment]
@khalilcodes 
image

**Pull request merged**
